#!/bin/bash
set -e

echo "SageMaker Deployment"
echo

AWS_REGION="${AWS_REGION:-ap-northeast-1}"
INSTANCE_TYPE="${INSTANCE_TYPE:-ml.g6.xlarge}"

# Try to read S3_MODEL_URI from .s3_model_uri file (generated by pack_model_to_s3.sh)
if [ -f ".s3_model_uri" ]; then
    S3_MODEL_URI=$(cat .s3_model_uri)
else
    S3_MODEL_URI="${S3_MODEL_URI:-}"
fi

echo -n "AWS Region [$AWS_REGION]: "
read -r input
AWS_REGION="${input:-$AWS_REGION}"

echo -n "AWS Account ID: "
read -r AWS_ACCOUNT_ID

echo -n "IAM Role ARN: "
read -r ROLE_ARN

echo -n "ECR Repository [financial-table-analysis]: "
read -r input
ECR_REPO="${input:-financial-table-analysis}"

echo -n "Image Tag [latest]: "
read -r input
IMAGE_TAG="${input:-latest}"

# S3 Model URI - prefer file/environment variable, fallback to user input
if [ -n "$S3_MODEL_URI" ]; then
    echo "S3 Model URI (from .s3_model_uri): $S3_MODEL_URI"
    echo -n "Use this S3 Model URI? (Y/n): "
    read -r input
    if [ "${input:-y}" != "y" ]; then
        echo -n "Enter S3 Model URI: "
        read -r S3_MODEL_URI
    fi
else
    echo -n "S3 Model URI (s3://bucket/path/model.tar.gz): "
    read -r S3_MODEL_URI
fi

echo -n "Instance Type [$INSTANCE_TYPE]: "
read -r input
INSTANCE_TYPE="${input:-$INSTANCE_TYPE}"

IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG"

echo
echo "Configuration:"
echo "  Region: $AWS_REGION"
echo "  Account: $AWS_ACCOUNT_ID"
echo "  Image: $IMAGE_URI"
echo "  Model URI: $S3_MODEL_URI"
echo
echo -n "Proceed? (y/N): "
read -r confirm

if [ "$confirm" != "y" ]; then
    exit 0
fi

echo && echo "Deploying endpoint..."
export ROLE_ARN IMAGE_URI S3_MODEL_URI AWS_REGION INSTANCE_TYPE
python3 scripts/deploy_endpoint.py

echo
echo "Done!"
